services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oms-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - oms-network
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: oms-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app  # or use selective mount with /app/node_modules
    networks:
      - oms-network
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    depends_on:
      - backend

networks:
  oms-network:
    driver: bridge
