[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for functions
[functions.environment]
  SUPABASE_URL = "https://trcrjinrdjgizqhjdgvc.supabase.co"

# API routes to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Health check
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

# Frontend SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 