[build]
  command = "npm run build:frontend"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BACKEND_URL = "https://your-railway-backend.railway.app/api/v1/trpc"

# Frontend SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 